{"name": "Проверка ручки post, что есть вход под логином существующего пользователя", "status": "passed", "start": 1732504719792, "stop": 1732504720720, "uuid": "a3e1e72c-22ce-47dc-bde3-f4a3ae4dd91f", "historyId": "6e65fa4bc1e9ad50f5c7bcab7bbca19f", "testCaseId": "6e65fa4bc1e9ad50f5c7bcab7bbca19f", "fullName": "tests.test_login_user.TestLoginUser#test_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-ME9CEU9"}, {"name": "thread", "value": "2972-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}